name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.18.1'

    - name: Install dependencies
      run: npm install --force --legacy-peer-deps

    - name: Verify Dependencies
      run: npm list

    - name: Build
      run: |
        CI=false npm run build

    - name: List Build Directory
      run: ls -la build

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Deploy
      run: npx gh-pages -d build
