name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  configure_git:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Git
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: configure_git
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.18.1'

    - name: Install dependencies
      run: npm install --force --legacy-peer-deps

    - name: Verify Dependencies
      run: npm list

    - name: Build
      run: |
        CI=false npm run build

    - name: List Build Directory
      run: ls -la build

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: npx gh-pages -d build
