name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_directory: ${{ steps.build.outputs.build_directory }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.18.1'

    - name: Install dependencies
      run: npm install --force --legacy-peer-deps

    - name: Verify Dependencies
      run: npm list

    - name: Build
      id: build
      run: |
        CI=false npm run build
        echo "::set-output name=build_directory::build"

    - name: List Build Directory
      run: ls -la build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Configure Git
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        git config --global user.email "${{ env.GH_EMAIL }}"
        git config --global user.name "${{ env.GH_USERNAME }}"

    - name: Verify Build Directory
      run: ls -la ${{ needs.build.outputs.build_directory }}

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: npx gh-pages -d ${{ needs.build.outputs.build_directory }}
